### ISSUE TITLE
Most Voted and Most Recent Buttons - Not click-able

### ISSUE THREAD

**Issue by achyutjoshi** [hyper-scale/race#56]
**Describe the bug**
The "Most Voted" and the "Most Recent" buttons in the home page are not click-able. 

**To Reproduce**
1. Go to https://race-blond.vercel.app/
2. Login in using Discord
3. Try clicking on either "Most Recent" or "Most Voted"

**Expected behavior**
The buttons should be click-able and respectively re-direct to their proper pages. 

**Screenshots**
<img width="615" alt="Screen Shot 2021-12-13 at 11 31 36 PM" src="https://user-images.githubusercontent.com/6535360/145953100-846291ef-bf38-47d5-8bdc-f1f4e5a3a3a7.png">

**Comment by mikefortney** [comment]
moved to trello
