### ISSUE TITLE
DAO Race: Leaderboard page UI > Application page

### ISSUE THREAD

**Issue by mhrnik** [hyper-scale/race#7]
DAO Race: Leaderboard page UI > Trending DAOs - Application page UI (HTML with static data)
![image](https://user-images.githubusercontent.com/8381252/145568908-94f4af80-2d7b-4f39-8329-fd65c93a45ea.png)

**Comment by mhrnik** [comment]
For design refer: https://www.figma.com/file/CPfZkeob1dtxStjSuUUXDs/HyperscalePaid?node-id=629%3A8268

**Comment by mhrnik** [comment]
We have new design: https://www.figma.com/file/CPfZkeob1dtxStjSuUUXDs/HyperscalePaid?node-id=0%3A1

**Comment by mikefortney** [comment]
Page has been built, data needs to be hooked up
