### ISSUE TITLE
Content screen height / floating footer

### ISSUE THREAD

**Issue by bmhtech07** [hyper-scale/race#84]
**Describe the bug**
Main content is not filling screen on /dao-race, leaving footer floating off bottom (display size 2560 x 1440).

Can be fixed by setting root / body div to .flex-col and main / content being .flex-grow.

![Screenshot 2021-12-16 at 12 59 55](https://user-images.githubusercontent.com/64862099/146376581-bad792c2-2c95-444b-a84c-b96ab75df510.png)

**Comment by mikefortney** [comment]
moved to trello
